[package]
name = "actix-multipart-derive"
version = "0.2.0"
authors = ["Jacob Halsey <jacob@jhalsey.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
darling = "0.14.1"
proc-macro2 = "1.0.37"
quote = "1.0.18"
syn = "1.0.92"
parse-size = "1.0.0"
