name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (nightly)
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: nightly
          components: rustfmt

      - run: cargo fmt --all -- --check

  clippy:
    permissions:
      checks: write # to add clippy checks to PR diffs

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          components: clippy

      - uses: giraffate/clippy-action@v1.0.1
        with:
          reporter: github-pr-check
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --workspace --all-features --tests --examples --bins -- -Dclippy::todo -Aunknown_lints

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (nightly)
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: nightly
          components: rust-docs

      - name: Check for broken intra-doc links
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo +nightly doc --no-deps --workspace --all-features

  check-external-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (nightly-2023-10-10)
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: nightly-2023-10-10

      - name: Install just
        uses: taiki-e/install-action@v2.20.2
        with:
          tool: just

      - name: Install cargo-check-external-types
        uses: taiki-e/cache-cargo-install-action@v1.2.2
        with:
          tool: cargo-check-external-types@0.1.10

      - name: check external types
        run: just check-external-types-all

  public-api-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - uses: actions/checkout@v4

      - name: Install Rust (nightly-2023-08-25)
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: nightly-2023-08-25

      - name: Install cargo-public-api
        uses: taiki-e/cache-cargo-install-action@v1.2.2
        with:
          tool: cargo-public-api@0.32.0

      - name: generate API diff
        run: |
          for f in $(find -mindepth 2 -maxdepth 2 -name Cargo.toml); do
            cargo public-api --manifest-path "$f" diff ${{ github.event.pull_request.base.sha }}..${{ github.sha }}
          done
